### ISSUE TITLE
Assumption about FQDN

### ISSUE THREAD

**Issue by jacobblock** [antevens/letsencrypt-freeipa#2]
Hi,

Thanks for the scripts. I ran into a couple of issues with an assumption that the IPA subdomain should be stripped from the top level domain. In my use case my freeipa server is still located at ipa.example.com. Not sure of a great way to configure for this, since for example the renew.sh has some bash function to strip this explicitly.

Thanks,

Jacob

**Comment by antevens** [comment]
Hi Jacob,

Sorry about being very very late at looking at this, my Github notifications were not correctly set.

I think the stripping is just meant to take the hostname off and leave the zone name but the code has changed a bit since you were testing.

I think the current relevant line would be:

ipa dnsrecord-add "${principal#[a-zA-Z0-9\-\_]*\.}." "_acme-challenge.${principal}." --txt-rec='INITIALIZED'

Is that what you're referring to?
